### ISSUE TITLE
Bad Pub.dev example

### ISSUE THREAD

**Issue by MarkOSullivan94** [solid-software/languagetool_textfield#60]
Firstly, congrats on an awesome package! ❤️

Right now [the example on pub.dev](https://pub.dev/packages/languagetool_textfield/example) is misleading in terms of how to use the package and so should be updated.

<img width="816" alt="Screenshot 2023-07-13 at 16 14 31" src="https://github.com/solid-software/languagetool_textfield/assets/6950843/01d1a1ba-bd4d-4eef-98cd-d1ec6ccbc2b8">

**Comment by illia-romanenko** [comment]
Thanks, should be fixed now.
